### ISSUE TITLE
Deciding on DocString style

### ISSUE THREAD

**Issue by sdhutchins** [datasnakes/Datasnakes-Scripts#122]
I think pycharm is using rest? docstring (for restructured text). @grabear 
```python
def function():
  """This function does something.

    :param name: The name to use.
    :type name: str.
    :param state: Current state to be in.
    :type state: bool.
    :returns:  int -- the return code.
    :raises: AttributeError, KeyError

    """
```
Are you okay with this format since you're already using similar? I'm going to work on adding to all the docstrings I've written. Won't be hard.

Also, there's an example [here](https://pythonhosted.org/an_example_pypi_project/sphinx.html#full-code-example). Since we're already using sphinx for documentation, I think it'd be great to use it.

**Comment by grabear** [comment]
Yea PyCharm uses Restructured text by default.  However, you can use the other ones as well:
![image](https://user-images.githubusercontent.com/20953530/32805498-3b64ae64-c94f-11e7-8f1e-015db1452df5.png)

But i do like restructured text.  So yea...
I'm unfamiliar with sphinx, but I'll look into when I do my next docstring patch.

**Comment by grabear** [comment]
Also PyCharm has some sphinx stuff built in:
![image](https://user-images.githubusercontent.com/20953530/32805637-a37fbf16-c94f-11e7-90df-22f44fcd87aa.png)

**Comment by sdhutchins** [comment]
Awesome. Yeah, Sphinx uses restructured text so it's a perfect fit. When I get ready to change those docstrings, I'll be sure to do in PyCharm. That seems significantly easier. I'll close out this issue now unless you have any more thoughts about code style.

**Comment by grabear** [comment]
Well you can check this box in PyCharm:
![image](https://user-images.githubusercontent.com/20953530/32806042-e35708fa-c950-11e7-81b8-ab55ad32bcf7.png)

And whenever you autogenerate the docstrings (trible-double quotes + ENTER), it will auto add the type.

But thats all I've got.

**Comment by sdhutchins** [comment]
That's very helpful. I'll have to make note of this when I start out.
