### ISSUE TITLE
Migrating Old Repository Issues and Projects

### ISSUE THREAD

**Issue by grabear** [datasnakes/Datasnakes-Scripts#27]
I'm just now getting to this...  I'm going to have to port over some of the projects, and issues from the old  [repository.](https://github.com/grabear/Orthologs-Project)  I want to delete it after we get some of those issues back in our field of view.  @sdhutchins Will this be a problem?

**Comment by grabear** [comment]
Sooooo...  uhhh... @sdhutchins I found a super simple tool for that...  https://github-issue-mover.appspot.com/

**Comment by sdhutchins** [comment]
@grabear That should be good. I just downloaded the old repo, and I’ll put it in the bioinformatics folder on the Vallender drive.

**Comment by sdhutchins** [comment]
@grabear test




Individuals who have received this information in error or are not authorized to receive it must promptly return or dispose of the information and notify the sender. Those individuals are hereby notified that they are strictly prohibited from reviewing, forwarding, printing, copying, distributing or using this information in any way.
