### ISSUE TITLE
Change ProjMana.__init__() 

### ISSUE THREAD

**Issue by grabear** [datasnakes/Datasnakes-Scripts#36]
So that anyone can use the base level project structure without having to also utilize RepoMana, WebMana, etc.  This will make it easier to manage projects individually, without having to create the entire framework aimed at FLASK.

**Comment by grabear** [comment]
@sdhutchins 
Working draft1:  https://github.com/datasnakes/Datasnakes-Scripts/commit/a27e7223f4057f8f26fb61f157dc247f498a8f58

**Comment by grabear** [comment]
Instructions:

1. After cloning my branch into the desired path use the below code to update it and then install it
```bash
git -C ~/desired/path/Datasnakes-Scripts/ pull
python36 -m pip install --user ~/desired/path/Datasnakes-Scripts --upgrade
```
2.  Use the following commands in a python console:
```python
import os
os.chdir('path')
from Datasnakes.Manager.utils import ProjMana
ProjMana(repo=None, user=None, project='SDH-Test1', new_project=True, home=os.getcwd(), research='GPCR', research_type='comparative_genetics', new_research=True, new_app=True, app='r_shiny')
```
@sdhutchins

**Comment by sdhutchins** [comment]
Looks good. I'll try it out in the am.

**Comment by grabear** [comment]
@sdhutchins Readme coming soon.

**Comment by grabear** [comment]
https://github.com/datasnakes/Datasnakes-Scripts/commit/176f88b55fe547165219be81308d98d0185ab030

**Comment by grabear** [comment]
basic project creation is also documented in the [Mini Tutorial](https://github.com/datasnakes/Datasnakes-Scripts/blob/cookie_jar_patch/Datasnakes/README.md)
