### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by grabear** [datasnakes/Datasnakes-Scripts#62]
https://github.com/datasnakes/Datasnakes-Scripts/commit/502f19768b614479dfa4eea6fa2abfb9622df216 @sdhutchins

**Comment by grabear** [comment]
Also here...  https://github.com/datasnakes/Datasnakes-Scripts/commit/06d34b28df4f2d3ec75983d1240502ca68fb70ad

**Comment by grabear** [comment]
https://github.com/datasnakes/Datasnakes-Scripts/commit/dbd1fe332e34220989a461ab5805b848e0fbf864#diff-ea1f65a8eaac0cec7ae151dfdbbbc587

**Comment by sdhutchins** [comment]
Good to know

**Comment by sdhutchins** [comment]
Addressed with PR #61
