### ISSUE TITLE
Remove `Archive` folder

### ISSUE THREAD

**Issue by sdhutchins** [datasnakes/Datasnakes-Scripts#66]
We need to migrate the archive folder to its own github repository and make it private. I think there are some insecure things in there (not sure if I removed them). @grabear 

Reference [this](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/).

**Comment by sdhutchins** [comment]
@grabear Do you want to handle this or would you like me to?

**Comment by grabear** [comment]
Go ahead! @sdhutchins I was going to leave it for tomorrow.

**Comment by sdhutchins** [comment]
Addressed by PR [#67](https://github.com/datasnakes/Datasnakes-Scripts/pull/67)
