### ISSUE TITLE
Abstract the configuration code in the Orthologs submodules

### ISSUE THREAD

**Issue by grabear** [datasnakes/Datasnakes-Scripts#75]
- CompGenObjects
- GenBank
- Alignment
- Soon to be Phylogenetics/PAML

All of these classes use the same configuration as seen in ff1cb04f88dfcf4d8d761cf7e9e4af7dbd560053.
It would help with readability to abstract these configurations into a function that exists elsewhere (utils.py?).

**Comment by sdhutchins** [comment]
That's a smart idea.

**Comment by sdhutchins** [comment]
Maybe a function called `config_check` or something related. That could be something we only use for the pipeline though.

**Comment by grabear** [comment]
Yes.  It would be nice to remove the spaghetti from __init__.  It makes everything look horrible.  It's been very useful though in converting to composition from direct inheritance.
(e.g. 13a560fd44dc6e83494cbd2fe2ec9b3c282453ed)

**Comment by grabear** [comment]
Here's the new abstracted configuration.  https://github.com/datasnakes/Datasnakes-Scripts/blob/Ortholog_config_patch/Datasnakes/Orthologs/utils.py

**Comment by grabear** [comment]
https://github.com/datasnakes/Datasnakes-Scripts/issues/93

**Comment by grabear** [comment]
All that's left is the PAML class.
